### ISSUE TITLE
Quality goals?

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet-data-svg#35]
Should we define on some quality goals and even try to check those in the CI or is that only hindering progress and we can fix up later?

A few ideas of quality goals I had:

# Match original as pixel perfect as possible

There could be tooling that generates diff images and recommended thresholds. Like shown in [this comment](https://github.com/ddnet/ddnet-data-svg/pull/27#issuecomment-995792862).

```
compare grass_main.png /usr/share/ddnet/data/mapres/grass_main.png -compose src diff.png
```

![image](https://user-images.githubusercontent.com/20344300/146376418-50eb7079-71e0-4b56-9d2d-37ba0c19892f.png)

# Correctness

This goal actually conflicts with the previous one. There are a few small things that look wrong in the original teeworlds textures should we try to fix them or keep them?

![image](https://user-images.githubusercontent.com/20344300/205356641-7c205d8f-4751-4248-9806-0cd15ed89aa4.png)

# File size and svg complexity

One can archive similar results with many nodes and with few nodes.
There are png to svg conversion tools should we use them or not?

![image](https://user-images.githubusercontent.com/20344300/205353104-562482a7-e1a9-4612-8979-3205e4394e2b.png)
![image](https://user-images.githubusercontent.com/20344300/205355675-4df92fe5-6a8d-4475-b31b-b762d5995cbc.png)

**Comment by def-** [comment]
Also if you "optimize" svgs you often lose information

**Comment by ChillerDragon** [comment]
> Also if you "optimize" svgs you often lose information

Yea sure there should never be a compromise for reducing complexity if there is a visible reduction of information. But if the svg is created by hand one can try to mimic the curves instead of spamming nodes. As seen in the screenshot. There are a lot of simple shapes where information can be kept.
