### ISSUE TITLE
giraffe

### ISSUE THREAD

**Issue by EwanGreen4** [ddnet/ddnet-data-svg#38]
please

**Comment by ChillerDragon** [comment]
Could you share the png file of the skin you would like to be converted?

**Comment by EwanGreen4** [comment]
[![image](https://user-images.githubusercontent.com/36348486/222980875-196e7fe1-4ef2-42fb-9799-e68037d91ac5.png)
](https://github.com/TeeworldsDB/skins/raw/master/06/giraffe.png)

**Comment by saltyElefant** [comment]
Here is my working file:

![giraffe_mind](https://user-images.githubusercontent.com/46008453/228502912-f73807d8-4e8f-4a57-9215-821b809cbc05.svg)


And here is a cleaned-up file:

![giraffe](https://user-images.githubusercontent.com/46008453/228503376-6fee4354-a6c0-444b-a921-a9678acf681a.svg)

**Comment by ChillerDragon** [comment]
> Here is my working file:
> 
> ![giraffe_mind](https://user-images.githubusercontent.com/46008453/228502912-f73807d8-4e8f-4a57-9215-821b809cbc05.svg)
> 
> And here is a cleaned-up file:
> 
> ![giraffe](https://user-images.githubusercontent.com/46008453/228503376-6fee4354-a6c0-444b-a921-a9678acf681a.svg)

If this is finished could you create a pullrequest?

**Comment by saltyElefant** [comment]
Yes, it is finished. Will do it later.

**Comment by EwanGreen4** [comment]
Thanks for doing this

**Comment by ChillerDragon** [comment]
Thanks @saltyElefant closed by https://github.com/ddnet/ddnet-data-svg/pull/43
