### ISSUE TITLE
[Question] What about files in "/data/maps/"?

### ISSUE THREAD

**Issue by M0REKZ** [ddnet/ddnet-data-svg#58]
Are these files also being considered? The maps have some embedded images inside and also are inside DDNet data folder, so technically this should be true, but still want to be sure.

**Comment by ChillerDragon** [comment]
Not sure which files you talk about. Could you name a specific one to avoid confusion.

**Comment by Jupeyy** [comment]
Not really worth it to add HD maps. The servers would need to host these HD variants and that probably would only be useful if a normal map & HD map could be hosted at the same time.

Better concentrate on actual images first, e.g. entities.

**Comment by M0REKZ** [comment]
> Not sure which files you talk about. Could you name a specific one to avoid confusion.

I talk about the images that are inside those maps, im wondering if these should be converted to svg too, but anyways, since Jupeyy said that seems like doing it wouldn't be very useful for the game itself.

**Comment by ChillerDragon** [comment]
Images in official ddnet maps? There is a chance we can just contact the authors maybe they have the files flying around. But yes I agree with jopsti recreating them manually does not seem to be worth the effort.

Especially if the images are embedded. How is that supposed to work? The client is supposed to use the embedded image and not bring his own images. A HD client would only work for external images. And replacing the embedded images in the official maps would affect map download times drastically.

**Comment by M0REKZ** [comment]
Ok so, seems that these images would not be very useful to make the game HD, however, it may be useful actually to make new mapres from it and use that for new maps, but looks like thats not the main purpose of the repo.

**Comment by ChillerDragon** [comment]
Closed as not planned for now.

@M0REKZ if you already have some svgs and look for a place to store them I started to collect any kind of mapres I can find as svg [here](https://github.com/TeeworldsDB/mapres/tree/f14516965e4affb4192b112e388c2b83f7910c0b/svg). As of right now its basically only one haha.
