### ISSUE TITLE
color inconsistency in grass_main.svg

### ISSUE THREAD

**Issue by WaRNe0nx3** [ddnet/ddnet-data-svg#61]
different colors have been used in two tiles compared to the rest of the tiles.

https://github.com/ddnet/ddnet-data-svg/blob/main/mapres/grass_main.svg
![2024-11-01_grassmainsvg](https://github.com/user-attachments/assets/e4d8419d-3d43-4c90-96c0-ebbb56683986)

**Comment by ChillerDragon** [comment]
Good catch! Thanks for reporting :heart: 

I fixed it by using the everywhere else color to keep the diff minimal.
